-- require("core.plugin_config.catpuccin")
require("core.plugin_config.colorscheme")
require("core.plugin_config.neosolarized")
require("core.plugin_config.lualine")
require("core.plugin_config.treesitter")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.gitsigns")
require("core.plugin_config.coc")
require("core.plugin_config.cheat")
require("core.plugin_config.prettier")
require("core.plugin_config.neoai")
-- require("core.plugin_config.luasnip")
